"""empty message

Revision ID: 338e5ac5577
Revises: 35795a8c3a4
Create Date: 2015-02-09 19:37:00.385314

"""

# revision identifiers, used by Alembic.
revision = '338e5ac5577'
down_revision = '35795a8c3a4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import lincoln


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.LargeBinary(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('total_in', lincoln.model_lib.SqliteNumeric(precision=1000, scale=28), nullable=True),
    sa.Column('total_out', lincoln.model_lib.SqliteNumeric(precision=1000, scale=28), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('output', sa.Column('address_hash', sa.LargeBinary(), nullable=True))
    op.create_index('ix_output_address_hash', 'output', ['address_hash'], unique=False)
    op.create_index('ix_output_origin_tx_hash', 'output', ['origin_tx_hash'], unique=False)
    op.create_index('ix_output_spend_tx_id', 'output', ['spend_tx_id'], unique=False)
    op.drop_column('output', 'dest_address')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('output', sa.Column('dest_address', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_index('ix_output_spend_tx_id', table_name='output')
    op.drop_index('ix_output_origin_tx_hash', table_name='output')
    op.drop_index('ix_output_address_hash', table_name='output')
    op.drop_column('output', 'address_version')
    op.drop_column('output', 'address_hash')
    op.drop_index('address_hash', table_name='address')
    op.drop_table('address')
    ### end Alembic commands ###
